<?php

namespace AppBundle\Repository;

/**
 * LgaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LgaRepository extends \Doctrine\ORM\EntityRepository
{
}
