<?php

namespace AppBundle\Repository;

use AppBundle\Entity\State;
use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository
{
    /**
     * @param $price
     * @return State[]
     */
    public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }
}
